# Generated by Django 4.0.1 on 2022-05-22 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cofbot', '0002_rename_id_barista_buying_barista_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buying',
            name='Barista',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='cofbot.barista'),
        ),
        migrations.AlterField(
            model_name='buying',
            name='Check',
            field=models.IntegerField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='buying',
            name='Cost',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='buying',
            name='Customer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='cofbot.profile'),
        ),
    ]
