# Generated by Django 4.0.1 on 2022-05-22 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cofbot', '0003_alter_buying_barista_alter_buying_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buying',
            name='Barista',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='cofbot.barista'),
        ),
        migrations.AlterField(
            model_name='buying',
            name='Check',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='buying',
            name='Cost',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='buying',
            name='Customer',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='cofbot.profile'),
        ),
    ]
