# Generated by Django 4.0.1 on 2022-06-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cofbot', '0005_provider_rename_id_ingred_recipe_ingred_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buying',
            name='Paid',
            field=models.BooleanField(default=False),
        ),
    ]
