# Generated by Django 4.0.1 on 2022-06-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cofbot', '0006_buying_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='buying',
            name='Datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
